CREATE TABLE [dbo].[ImageSettings](
	[ImageType] [nvarchar](100) NOT NULL,
	[Image] [nvarchar](max) NULL,
 CONSTRAINT [PK_ImageSettings] PRIMARY KEY CLUSTERED 
(
	[ImageType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]