CREATE TABLE [dbo].[ScriptSetting](
	[id] [int] NOT NULL,
	[PageTitle] [nvarchar](max) NULL,
 CONSTRAINT [PK_ScriptSetting] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]