CREATE TABLE [dbo].[URL_Setting](
	[Type] [nvarchar](100) NOT NULL,
	[URL] [nvarchar](max) NULL,
 CONSTRAINT [PK_URL_Setting] PRIMARY KEY CLUSTERED 
(
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]