CREATE TABLE [dbo].[UserRoleMetric](
	[UserName] [nvarchar](100) NOT NULL,
	[UserRoleID] [bigint] NOT NULL,
 CONSTRAINT [PK_UserRoleMetric] PRIMARY KEY CLUSTERED 
(
	[UserName] ASC,
	[UserRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]