CREATE                 VIEW [dbo].[vw_SQLValuerDPSubmission] AS


SELECT [ARN]
      ,[ValuerCode]
      ,[ValuerReportAttachmentURL]
      ,[ValuerReportAttachment]
      ,[ValuerReportAttachmentDate]
      ,[VRInstructionDate]
      ,[ValuerReference]
      ,[PersonInChargeName]
      ,[VUpdateInfoStatus]
      ,[VLowerOMVStatus]
      ,[VUpdateInfoStatusOthers]
      ,[VLowerOMVReasons]
      ,[DateOfValuation]
      ,[MarketValue]
      ,[FireInsuranceValue]
      ,[InvoiceNumber]
      ,[ShortfallAmount]
      ,[Declaration]
      ,[Status]
      ,[ValuationFeeFinancedByBankFlag]
      ,[LF_PayeeName]
      ,[LF_BilledAmount]
      ,[LF_AccountNumber]
      ,[LF_Bank]
      ,[LF_PaymentDescription]
      ,[LF_PaymentMode]
      ,[Completed]
      ,[OutputPDFID]
      ,[CreatedDate]
      ,[UpdatedDate]
  FROM [dbo].[SQLValuerDPSubmission]
  union 
  
SELECT [ARN]
      ,[ValuerCode]
      ,[ValuerReportAttachmentURL]
      ,[ValuerReportAttachment]
      ,[ValuerReportAttachmentDate]
      ,[VRInstructionDate]
      ,[ValuerReference]
      ,[PersonInChargeName]
      ,[VUpdateInfoStatus]
      ,[VLowerOMVStatus]
      ,[VUpdateInfoStatusOthers]
      ,[VLowerOMVReasons]
      ,[DateOfValuation]
      ,[MarketValue]
      ,[FireInsuranceValue]
      ,[InvoiceNumber]
      ,[ShortfallAmount]
      ,[Declaration]
      ,[Status]
      ,[ValuationFeeFinancedByBankFlag]
      ,[LF_PayeeName]
      ,[LF_BilledAmount]
      ,[LF_AccountNumber]
      ,[LF_Bank]
      ,[LF_PaymentDescription]
      ,[LF_PaymentMode]
      ,[Completed]
      ,[OutputPDFID]
      ,[CreatedDate]
      ,[UpdatedDate]
  FROM [dbo].[SQLValuerDPSubmission_staging]