CREATE     procedure [dbo].[ddProjectDisbursementSubmission_DisMaker_GetRejected_ByARN]
@arn nvarchar(100) = null ,
@billingid bigint = null 
as
begin

	/*
	SELECT solsub.[arn]
		,solsub.[BalanceAdviceLetterApplicableFlag]
		,solsub.[UrgentFlag]
		,solsub.[LS_RedemptionDueDateFlag]
		,solsub.[LS_RedemptionDueDate]
		,solsub.[LS_ExtendedCompletionDateFlag]
		,solsub.[LS_CompletionDate]
		,solsub.[LS_ExtendedCompletionDate]
		,solsub.[PR_DeveloperBillingDueDateFlag]
		,solsub.[PR_Stage2AFlag]
		,solsub.[PR_Stage2BFlag]
		,solsub.[PR_Stage2CFlag]
		,solsub.[PR_Stage2DFlag]
		,solsub.[PR_Stage2EFlag]
		,solsub.[PR_Stage2FFlag]
		,solsub.[PR_Stage2GFlag]
		,solsub.[PR_Stage2HFlag]
		,solsub.[PR_StageOthers]
		,solsub.[PR_EarliestBillingDueDate]
		,solsub.[PR_TotalBillingAmount]
		,solsub.[PR_AnyBridgingFinancierFlag]
		,solsub.[PR_BridgingFinancier]
		,solsub.[PR_BridgingFinancierEmailAddress]
		,solsub.[PR_BridgingFinancierRedemptionSum]
		,solsub.[PR_RedemptionPaymentAccountNumber]
		,solsub.[PR_BeneficiaryBank]
		,solsub.[PR_BridgingFinancierRedemptionExpiryDate]
		,solsub.[PR_DeveloperName]
		,solsub.[PR_DeveloperEmailAddress]
		,solsub.[PR_DeveloperPIC]
		,solsub.[PR_DeveloperHDA]
		,solsub.[PR_DeveloperHDABank]
		,solsub.[LF_PayeeName]
		,solsub.[LF_BilledAmount]
		,solsub.[LF_AccountNumber]
		,solsub.[LF_Bank]
		,solsub.[LF_PaymentDescription]
		,solsub.[LF_PaymentMode]
		,solsub.[UpdateInfo_Reason]
		,solsub.[UpdateInfo_Others]
		,solsub.[CancelLoan_Remarks]
		,solsub.[CancelLoan_File]
		,solsub.[SolicitorSubmissionOption]
		,solsub.[SolicitorSubmissionCompleted]
		,solsub.[SolicitorCode]
		,solsub.[SolicitorSubmissionDate]
		,solsub.[SolicitorSubmissionPDFID]
		--,solsub.[DisbursementMakerEmailAddress]
		,InternalUser_maker.UserFullName as DisbursementMakerEmailAddress
		,solsub.[DisbursementMakerDecision]
		,solsub.[DisbursementMakerSubmissionCompleted]
		,solsub.[DisbursementMakerRejectionReason]
		,solsub.[DisbursementMakerSubmissionDate]
		,solsub.[DisbursementMakerSubmissionPDFID]
		,solsub.[DisbursementCheckerEmailAddress]
		,solsub.[DisbursementCheckerDecision]
		,solsub.[DisbursementCheckerSubmissionCompleted]
		,solsub.[DisbursementCheckerRejectionReason]
		,solsub.[DisbursementCheckerSubmissionDate]
		,solsub.[DisbursementCheckerPDFID]
		,solsub.[CreatedDate]
		,solsub.[UpdatedDate]
		--,case when history.arn IS NOT NULL then 'Balance Advice' ELSE '1st Advice'  end as 'Disbursement Stage'		
		*/
	SELECT solsub.[arn]
      ,[BalanceAdviceLetterApplicableFlag]
      ,[UrgentFlag]
      ,[LS_RedemptionDueDateFlag]
      ,[LS_RedemptionDueDate]
      ,[LS_ExtendedCompletionDateFlag]
      ,[LS_CompletionDate]
      ,[LS_ExtendedCompletionDate]
      ,[PR_DeveloperBillingDueDateFlag]
      ,solsub.[PR_Stage2AFlag]
      ,solsub.[PR_Stage2BFlag]
      ,solsub.[PR_Stage2CFlag]
      ,solsub.[PR_Stage2DFlag]
      ,solsub.[PR_Stage2EFlag]
      ,solsub.[PR_Stage2FFlag]
      ,solsub.[PR_Stage2GFlag]
      ,solsub.[PR_Stage2HFlag]
      ,solsub.[PR_StageOthers]
      ,solsub.[PR_EarliestBillingDueDate]
      ,solsub.[PR_TotalBillingAmount]
      ,[PR_AnyBridgingFinancierFlag]
      ,[PR_BridgingFinancier]
      ,[PR_BridgingFinancierEmailAddress]
      ,[PR_BridgingFinancierRedemptionSum]
      ,[PR_RedemptionPaymentAccountNumber]
      ,[PR_BeneficiaryBank]
      ,[PR_BridgingFinancierRedemptionExpiryDate]
      ,[PR_DeveloperName]
      ,[PR_DeveloperEmailAddress]
      ,[PR_DeveloperPIC]
      ,[PR_DeveloperHDA]
      ,[PR_DeveloperHDABank]
      ,[LF_PayeeName]
      ,[LF_BilledAmount]
      ,[LF_AccountNumber]
      ,[LF_Bank]
      ,[LF_PaymentDescription]
      ,[LF_PaymentMode]
      ,[UpdateInfo_Reason]
      ,[UpdateInfo_Others]
      ,[CancelLoan_Remarks]
      ,[CancelLoan_File]
      ,[SolicitorSubmissionOption]
      ,[SolicitorSubmissionCompleted]
      ,[SolicitorCode]
      ,[SolicitorSubmissionDate]
      ,[SolicitorSubmissionPDFID]
      ,[DisbursementMakerEmailAddress]
      ,[DisbursementMakerDecision]
      ,[DisbursementMakerSubmissionCompleted]
      ,[DisbursementMakerRejectionReason]
      ,[DisbursementMakerSubmissionDate]
      ,[DisbursementMakerSubmissionPDFID]
      ,[DisbursementCheckerEmailAddress]
      ,[DisbursementCheckerDecision]
      ,[DisbursementCheckerSubmissionCompleted]
      ,[DisbursementCheckerRejectionReason]
      ,[DisbursementCheckerSubmissionDate]
      ,[DisbursementCheckerPDFID]
      ,[RCOMakerEmailAddress]
      ,[RCOMakerDecision]
      ,[RCOMakerSubmissionCompleted]
      ,[RCOMakerRejectionReason]
      ,[RCOMakerSubmissionDate]
      ,[RCOMakerPDFID]
      ,[RCOCheckerEmailAddress]
      ,[RCOCheckerDecision]
      ,[RCOCheckerSubmissionCompleted]
      ,[RCOCheckerRejectionReason]
      ,[RCOCheckerSubmissionDate]
      ,[RCOCheckerPDFID]
      ,solsub.[CreatedDate]
      ,solsub.[UpdatedDate]
      ,solsub.[FinalBillingFlag]
      ,[ProjectSubmissionOption]
      ,[ProjectSubmissionCompleted]
      ,solsub.[DeveloperCode]
      ,solsub.[ProjectCode]
      ,solsub.[PhaseCode]
      ,solsub.[DeveloperLoginID]
      ,[ProjectSubmissionDate]
      ,[ProjectSubmissionPDFID]
      ,solsub.[PR_Stage2IFlag]
      ,solsub.[PR_Stage2JFlag]
      ,solsub.[PR_Stage2KFlag]
      ,solsub.[PR_Stage3]
      ,solsub.[PR_Stage4]
      ,solsub.[PR_Stage5]
      ,solsub.[PR_Stage6]
      ,solsub.[PR_Stage7]
      ,solsub.[PR_Stage8]
      ,solsub.[PR_Stage9]
      ,solsub.[Attachment1]
      ,solsub.[Attachment2]
      ,solsub.[DraftID]
      ,[SadaFlag]
      ,[ConfirmationOfArchitectFlag]
      ,[ConfirmationOfArchitectRemark]
      ,[BillingRunningID]
      ,solsub.[PrimaryCustomerName]
      ,solsub.[FinancingAmount]
      ,solsub.[AddressLine1]
      ,solsub.[ExtraField1]
      ,solsub.[ExtraField2]
      ,solsub.[ExtraField3]
      ,solsub.[ExtraField4]
      ,[RejectedRunningID]
      ,[SPADate]
      ,[SPAConstructionPeriodInMonths]
      ,[ExtendedConstructionPeriodInMonths]
	  , history_draft_master.PR_Stage2AFlag as DeveloperInput_PR_Stage2AFlag
	  , history_draft_master.PR_Stage2BFlag as DeveloperInput_PR_Stage2BFlag
	  , history_draft_master.PR_Stage2CFlag as DeveloperInput_PR_Stage2CFlag
	  , history_draft_master.PR_Stage2DFlag as DeveloperInput_PR_Stage2DFlag
	  , history_draft_master.PR_Stage2EFlag as DeveloperInput_PR_Stage2EFlag
	  , history_draft_master.PR_Stage2FFlag as DeveloperInput_PR_Stage2FFlag
	  , history_draft_master.PR_Stage2GFlag as DeveloperInput_PR_Stage2GFlag
	  , history_draft_master.PR_Stage2HFlag as DeveloperInput_PR_Stage2HFlag
	  , history_draft_master.PR_Stage2IFlag as DeveloperInput_PR_Stage2IFlag
	  , history_draft_master.PR_Stage2JFlag as DeveloperInput_PR_Stage2JFlag
	  , history_draft_master.PR_Stage2KFlag as DeveloperInput_PR_Stage2KFlag
	  , history_draft_master.PR_Stage3 as DeveloperInput_PR_Stage3
	  , history_draft_master.PR_Stage4 as DeveloperInput_PR_Stage4
	  , history_draft_master.PR_Stage5 as DeveloperInput_PR_Stage5
	  , history_draft_master.PR_Stage6 as DeveloperInput_PR_Stage6
	  , history_draft_master.PR_Stage7 as DeveloperInput_PR_Stage7
	  , history_draft_master.PR_Stage8 as DeveloperInput_PR_Stage8
	  , history_draft_master.PR_Stage9 as DeveloperInput_PR_Stage9
	  , history_draft_master.PR_StageOthers as DeveloperInput_PR_StageOthers
	  , history_draft_master.PR_EarliestBillingDueDate as DeveloperInput_PR_EarliestBillingDueDate
	  , history_draft_master.FinalBillingFlag as DeveloperInput_FinalBillingFlag
	  , history_draft_individual.BillingAmount as DeveloperInput_BillingAmount
	FROM [dbo].ddProjectDisbursementSubmission_DisMaker_Rejected solsub
		left join ddProjectDisbursementSubmission_draft_Master_History history_draft_master on history_draft_master.DraftID = solsub.DraftID 
		left join ddProjectDisbursementSubmission_draft_History history_draft_individual on history_draft_individual.DraftID = solsub.DraftID and history_draft_individual.arn = solsub.arn
		left join InternalUser InternalUser_maker on InternalUser_maker.UserName = solsub.DisbursementMakerEmailAddress
	where solsub.arn = @arn 
		and BillingRunningID = @billingid
end